### ISSUE TITLE
Mergui updated

### ISSUE THREAD

**Issue by lenscas** [xipi2048/the_net#1]
It looked like you wanted to use Mergui with the latest version of quicksilver. I updated Mergui to target the latest quicksilver so it should be easier now. Just put
```
mergui = "0.1.0-alpha0.8"
```
in the Cargo.toml file.

I did the same for silver_animation. To use it, put 
```
silver_animation = "0.1"
```
in the Cargo.toml file.

The update(s) don't contain any other changes.

**Comment by xipi2048** [comment]
Awesome thanks @lenscas. Will look into updating :)

**Comment by lenscas** [comment]
One warning though: The CI seems to have broken on those 2 repo's. They where also not setup to work with wasm-bindgen (I never used that) and std-web seems to have broken in one of quicksilvers dependencies. 

So, though everything *should* still work, and I can see that locally native builds still do its hard to verify. Either way, if you run into issues just let me know and I'll see what I can do :)

**Comment by xipi2048** [comment]
Hmm okay. I was hoping to target wasm. Any idea how much work would be involved with setting that up?

**Comment by lenscas** [comment]
you can still target wasm. Just seems that std-web isn't working out of the box anymore. Wasm-bindgen should still work, but as I already said I never used it. The plan was to move to wasm-bindgen in quicksilver anyway (https://github.com/ryanisaacg/quicksilver/issues/653) and as std-web is both less popular and doesn't seem to get updates I would recommend to use that.

I doubt that either Mergui or Silver_animation have problems with wasm-bindgen. The stdweb feature they both have just enables the quicksilver one. At the time when I wrote the CI for them I didn't know you could enable a feature in a dependency through the command line, so that is why they exist.

**Comment by xipi2048** [comment]
Awesome sounds good. Thanks @lenscas

Thank you,
.
..: Raen

________________________________

**Comment by xipi2048** [comment]
Going to be trying mergui with my next project. Want to keep the dependencies down on this one
